source 'https://rubygems.org'

gem 'activesupport'
gem 'addressable'
gem 'capybara'
gem 'chromedriver-helper'
gem 'faker'
gem 'faraday'
gem 'faraday_middleware'
gem 'filewatcher'
gem 'git'
gem 'json_roa-client', '>= 1.0.0', '< 2.0.0'
gem 'poltergeist'
gem 'pry'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver'
