source 'https://rubygems.org'

gem 'activesupport'
gem 'addressable'
gem 'capybara', '>= 2.13.0', '< 3.0.0'
gem 'chromedriver-helper', '>= 1.1.0', '< 2.0.0'
gem 'faker'
gem 'faraday'
gem 'faraday_middleware'
gem 'filewatcher'
gem 'git'
gem 'json_roa-client', '>= 1.0.0', '< 2.0.0'
# gem 'poltergeist'
gem 'pry'
gem 'rest-client'
gem 'rspec'
gem 'selenium-webdriver', '>= 3.4.0', '< 4.0.0'
