var TopLevel = {
"app" : function () {},
"BrowserWindow" : function () {},
"console" : function () {},
"crashReporter" : function () {},
"Error" : function () {},
"existsSync" : function () {},
"kill" : function () {},
"loadURL" : function () {},
"log" : function () {},
"on" : function () {},
"platform" : function () {},
"quit" : function () {},
"resolve" : function () {},
"setTimeout" : function () {},
"spawn" : function () {},
"start" : function () {},
"stderr" : function () {},
"stdout" : function () {},
"type" : function () {}
}